route:
  group_by: ['alertname']
  group_wait: 2s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'python-healer'

receivers:
  - name: 'python-healer'
    webhook_configs:
      - url: 'http://sre_agent:8001/api/webhook/alert'
        send_resolved: true
