events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=2r/s;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        location /api/agent/ {
            limit_req zone=api_limit burst=5 nodelay;
            proxy_pass http://sre_agent:8001;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
        }

        location /api/ {
            limit_req zone=api_limit burst=5 nodelay;
            
            # DNS-резолвер Docker (по умолчанию 127.0.0.11). 
            # Заставляет Nginx обновлять IP адреса бэкендов каждые 2 секунды.
            resolver 127.0.0.11 valid=2s;
            set $backend "http://app:8000";
            proxy_pass $backend;
            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
        }
    }
}
