events {
    worker_connections 1024;
}

http {
    include /etc/nginx/blocklist.conf;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=2r/s;

    upstream api_backend {
        server app:8000;
        keepalive 64; # Пул соединений для предотвращения TCP Port Exhaustion
    }

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        location /api/agent/ {
            limit_req zone=api_limit burst=5 nodelay;
            proxy_pass http://sre_agent:8001;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
        }

        location /api/internal_heavy {
            # Специальный роут для нашего внутреннего DDoS теста без Rate Limit.
            # Теперь используем статический апстрим с Keep-Alive для предотвращения port exhaustion
            proxy_pass http://api_backend/api/heavy;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location /api/ {
            limit_req zone=api_limit burst=5 nodelay;
            
            # Используем пул соединений
            proxy_pass http://api_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
        }
    }
}
