{
 "title": "SRE Defense Control Panel",
 "tags": [
  "sre",
  "chaos-engineering"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[10s]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "API Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[10s])) / sum(rate(http_request_duration_seconds_count[10s]))",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "Backend CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"sre-backend\"}[10s]) * 100",
     "legendFormat": "Node {{instance}}"
    }
   ]
  },
  {
   "title": "Backend Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"sre-backend\"} / 1024 / 1024",
     "legendFormat": "Node {{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Nodes Status",
   "type": "state-timeline",
   "gridPos": { "x": 0, "y": 18, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "up{job=\"sre-backend\"}",
     "legendFormat": "Node {{instance}}"
    }
   ]
  },
  {
   "title": "Active Replicas History",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 18, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(up{job=\"sre-backend\"})",
     "legendFormat": "Total Online"
    }
   ]
  },
  {
   "title": "Blocked Threats (Honeypot)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 18, "w": 8, "h": 6 },
   "targets": [
    { "expr": "sre_blocked_threats_total", "legendFormat": "Blocked IPs" }
   ]
  }
 ]
}